language: objective-c
osx_image: xcode10.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=MessagingApp.xcworkspace
  - SCHEME=MessagingApp
  - SDK=iphonesimulator12.4
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=12.4,name=iPhone XS"
    - DESTINATION="OS=11.4,name=iPhone X"

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/MessagingApp-*/
- rvm use $RVM_RUBY_VERSION

install:
# read gemfile in same folder and install gems
- bundle install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

after_success: slather
